### ISSUE TITLE
Asynchronous PgRowSet

### ISSUE THREAD

**Issue by yonigibbs** [reactiverse/reactive-pg-client#146]
Hi,

This is just a question, not really an issue.  Apologies if this isn't the right way/forum to ask this...

In the documentation it states "Query methods provides an asynchronous PgRowSet instance that works for SELECT queries".  Could you please clarify what you mean exactly by asynchronous here?  I take it that this doesn't refer to records being supplied "one-by-one" as they are returned from the query (like in a [Flux](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html))?  In other words, by the time you get a `PgRowSet` back, all the records are already in memory in it?

Assuming that's correct, how exactly would you get a Flux of records?  From what I can see, if you use `PgPool.query` that will return all records in one go.  So to get a Flux, you could instead use `PgPreparedQuery.createStream`, asking for X records back at a time.  That way you could simulate a Flux which produces X items at a time.

Is that correct, or have I misunderstood something?

If all correct, do you have any ideas if using the latter approach (creating a stream, which involves using a cursor and therefore creating a transaction) has any performance impact compared with just running a query directly?  For example, should we avoid this approach unless working with larger data sets?

Thanks in advance!

**Comment by vietj** [comment]
yes you are totally right, as you said

- `PgRowSet` load all results in memory, which makes sense because the protocol will send the results on the wire and there is no way to control it
- `PgStream` uses a cursor to load the results by batches and can be mapped to a Reactive Streams publisher, which is what you get when you use an RxJava 2 `Flowable` with the rx-ified API

By asynchronous we mean that getting the query result does not block the thread and the application will get an event notifying the result (as a `PgResult`).

Applying back-pressure on `PgRowSet` is not a great idea when you need concurrency because the connection will remain used (since there will be unread bytes on the wire) and that will create a bottleneck in your application (since other requests might wait for a connection). Connections are unfortunately not multiplexed.

Here are some guidelines:

- if you have very large result set and you cannot afford cursors then the best is to use `PgRowSet` and paginate results using SQL
- if you can afford cursor, then you should use `PgStream`. The cost of a cursor depends on your environment, db tuning, etc...

My advice is that you should write a simple benchmark to test what works best for you.

**Comment by yonigibbs** [comment]
Great stuff, that all makes perfect sense. Thanks for the quick answer, Julien.
